### ISSUE TITLE
Мифист

### ISSUE THREAD

**Issue by MakeevIvan** [agsh/mephi15-2#10]
Здравствуйте!
У меня вместе с Рудановым Михаилом (варианты 5 и 9) возникли проблемы с кодировкой мифиста. 
Пробовали использовать пакеты Data.ByteString  и Data.Text.Encoding не удалось разобраться с этой проблемой. Показываются не понятные символы, не используя данные пакеты выводятся цифры. Прикладываем скриншот. 
Как справиться с этой проблемой? или можно ли поменять вариант на англоязычный сайт?
![2015-12-21 10 45 52](https://cloud.githubusercontent.com/assets/11290926/11925796/12735926-a7d0-11e5-8b68-c08916eaf895.png)

**Comment by agsh** [comment]
Делаем `cabal install encoding`, `cabal install http`, если у вас нет `Data.Encoding` и `Network.HTTP`.
И дальше вот пример:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import Network.HTTP
import Data.Encoding
import Data.Encoding.CP1251

mephist = do
        text <- simpleHTTP (getRequest "http://www.mephist.ru")
        rText <- fmap (decodeString CP1251) (getResponseBody text)
        putStr rText
```
