### ISSUE TITLE
Проблема с javascript 

### ISSUE THREAD

**Issue by anita-balandina** [agsh/mephi15-2#11]
Возникли проблемы с 17 вариантом. Если страницы человека с определенным ником на гитхабе нет, то вместо того, чтобы парсить страницу, выкидывается exception, потому что срабатывает javascript error.js. Как решить эту проблему?

**Comment by agsh** [comment]
А можно пример кода?

**Comment by anita-balandina** [comment]
searchTitle :: Cursor -> [Cursor]
searchTitle = element "html" &// element "head" &// element "title" >=> child

Если такой человек есть на гитхабе вернет его никнейм и имя, если нет, вылетит эксепшен.

**Comment by agsh** [comment]
Мне бы полный код, посмотреть, что за исключение

**Comment by anita-balandina** [comment]
https://gist.github.com/anita-balandina/9fa0ed20a4ddea65aa37

**Comment by agsh** [comment]
Можно отлавливать это исключение и возвращать пустую строку:

``` haskell
cursorFor u = do
     page <- (withSocketsDo $ simpleHttp u) `catch` badUrl
     return $ fromDocument $ parseLBS page

badUrl :: HttpException -> IO L.ByteString
badUrl e = (putStrLn $ show e) >> (return L.empty)
```
