### ISSUE TITLE
Exception: Too many requests

### ISSUE THREAD

**Issue by InsomniaNoctis** [agsh/mephi15-2#13]
Здравствуйте! Я парсю все 35 страниц (вариант 18), с профилями пользователей.
Каждый раз выбрасывается эксепшен "Too many requests". При меньшем количестве страниц (до 7) парсинг работает нормально.
Как решить эту проблему?

**Comment by agsh** [comment]
Можно попробовать после каждого запроса, или после каждых пяти делать паузу в текущем потоке.
`cabal install concurrent-extra`

``` haskell
import Control.Concurrent.Thread.Delay
main = putStr "Hi " >> delay 5000000 >> putStr "there!"
```
