### ISSUE TITLE
Проблемы с получением данных из Вконтакте

### ISSUE THREAD

**Issue by LazarevSergey** [agsh/mephi15-2#14]
Здравствуйте! Проблема с авторизацией для получения данных. Требуются или куки, у которой быстро истекает срок годности, или аксес токен, который тяжело получить. Возможно ли заменить задание?

**Comment by agsh** [comment]
Какой номер задания?

**Comment by LazarevSergey** [comment]
10

**Comment by agsh** [comment]
Поменял задание
