### ISSUE TITLE
Опять Мифист

### ISSUE THREAD

**Issue by mrudanov** [agsh/mephi15-2#15]
decodeString хорошо правильно работает, когда мы извлекаем текст страницы так, как вы указали. Но если мы парсим страницу, используя Cursor, извлекать данные мы можем используя attribute или content, которые возвращают Text (а не String). Чтобы перекодировать Text в String используем функцию Text.unpack, тут и происходит самый ахтунг: все символы из кириллицы он заменяет одним и тем же символом \65533, который decodeString'ом переводится в символ 'М'. Выходит, получаем страницу, имеющую одинаковые символы 'М', вместо кириллических символов. Миновать стадию Cursor -> Text -> String невозможно, так как в пакете Text.XML.Cursor нет функции Cursor -> String. Также прикрепляю скрин, демонстрирующий, что на этапе Cursor -> Text -> String все символы кириллицы заменяются на один и тот же.
<img width="760" alt="screen shot 2015-12-23 at 22 30 52" src="https://cloud.githubusercontent.com/assets/11590187/11983489/e29c1d0e-a9c4-11e5-8018-f2cca19935ae.png">

**Comment by agsh** [comment]
А вам вместо Char8 нужно использовать UTF-8. Держите полный работающий пример:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import Network.HTTP
import Data.Encoding
import Data.Encoding.CP1251
import Network.HTTP.Conduit
import qualified Data.ByteString.Lazy.UTF8 as L
import qualified Data.Text as T
import Text.HTML.DOM (parseLBS)
import Text.XML.Cursor (Cursor, attributeIs, content, element, fromDocument, child, ($//), (&|), (&//), (&/), (>=>))

mephist = do
        text <- simpleHTTP (getRequest "http://www.mephist.ru")
        rText <- fmap (decodeString CP1251) (getResponseBody text)
    let lText = L.fromString rText
    return $ fromDocument $ parseLBS lText

findNodes :: Cursor -> [Cursor]
findNodes = element "div" >=> attributeIs "class" "quote" >=> child

extractData :: Cursor -> T.Text
extractData = T.concat . content

search = do
    cursor <- mephist
    let infoNodes = cursor $// findNodes &| extractData
    let text = (T.unpack . T.concat) infoNodes
    return text

main = do
    text <- search
    putStr text
```
