### ISSUE TITLE
Получение данных со страницы с новостями с сайта mephi.ru

### ISSUE THREAD

**Issue by LazarevSergey** [agsh/mephi15-2#16]
Вариант 10. Не могу получить даты выложенных новостей с сайта МИФИ со всех страниц кроме страницы 1, так как способ перехода между страницами новостей реализован следующим образом: 

![default](https://cloud.githubusercontent.com/assets/7592276/12003727/a4f48cf6-ab3c-11e5-8666-12e4b3569543.PNG)

а PAGEN все время меняется.
Что делать? На данный момент вывод производится только по первой странице.

**Comment by agsh** [comment]
Перебирать `PAGEN_1`, пока не вылезет исключение
