### ISSUE TITLE
20 вариант

### ISSUE THREAD

**Issue by Kazbek** [agsh/mephi15-2#2]
Мне кажется ссылка испортилась, 3 лаба https://www.linux.org.ru/wiki/en/%D0%A7%D0%B0%D1%81%D1%82%D1%8C_1._%D0%9E%D0%B1%D1%89%D0%B8%D0%B5_%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B_%D0%BE_Lisp
![image](https://cloud.githubusercontent.com/assets/15718432/11289481/50ea400c-8f3e-11e5-9713-b7caa828e4c8.png)

**Comment by agsh** [comment]
Да, переехала на лорвики. Исправил задание.
