### ISSUE TITLE
mephist

### ISSUE THREAD

**Issue by mrudanov** [agsh/mephi15-2#3]
Доброе времени суток! Имею 9 вариант, нужно вывести 50 комментариев лучших преподавателей. Возник вопрос: что на mephist называется комментарием? Нашел там только отзывы, надо выводить их?
![screen shot 2015-12-11 at 20 13 16](https://cloud.githubusercontent.com/assets/11590187/11750455/84de371c-a044-11e5-9b70-63a92cc57d12.png)

**Comment by agsh** [comment]
Да, задание получилось неоднозначное. Подкорректировал его.
