### ISSUE TITLE
Вопрос по лабе 3 (вариант 6)

### ISSUE THREAD

**Issue by mour12** [agsh/mephi15-2#8]
На самом сайте кафедры информации о страницах в соц сетях нет. Нужно будет самому через APIs искать их?

Если да, то предполагаю, что определяться, что страница в соц. сети относится к преподавателю, будет по совпадению ФИО с ФИО преподавателя и местом работы МИФИ. Что делать, если таких страниц несколько? Что делать, если таких страниц не обнаружено?

**Comment by agsh** [comment]
Да, через API. Можно ограничиться какой-либо одной соц.сетью (что-то задание сложным получается). Соответственно, использовать список: пусой - страниц не обнаружено, несколько - набор url
